### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by 6oody** [B3akers/LeagueSkinChanger#33]
it just opens after the last patch v11.1, and when it doesn't inject or some times it does but not working when i press ' insert butt ' 
nothing happens
![unknown](https://user-images.githubusercontent.com/42409047/103953293-883c1200-514a-11eb-96b7-fced5523c513.png)

**Comment by 6oody** [comment]
fix it please when u see this @B3akers @PythonTryHard

**Comment by CreativeHell** [comment]
i think they changed the offsets or smth

**Comment by 6oody** [comment]
> i think they changed the offsets or smth

idk but i just hate lol skin so i wanna they fix this injector to stop using lol skin

**Comment by PythonTryHard** [comment]
@6oody While the issue can be replicated on my end with a v11.1 client (`Insert` key does not bring up skin changing menu), please supply the final state of the injector (showing whether injection was successful or not) instead of when the injector is waiting for the League client process. 

Unfortunately, I am not equipped enough to "fix" this since I lack the knowledge of the code's inner working as well as the tools and method used to inject. 

> fix it please when u see this
A gentle reminder that begging for a fix does not help making such fix become available faster. It gets out when it gets out.

**Comment by 6oody** [comment]
> @6oody While the issue can be replicated on my end with a v11.1 client (`Insert` key does not bring up skin changing menu), please supply the final state of the injector (showing whether injection was successful or not) instead of when the injector is waiting for the League client process.
> 
> Unfortunately, I am not equipped enough to "fix" this since I lack the knowledge of the code's inner working as well as the tools and method used to inject.
> 
> > fix it please when u see this
> 
> And a gentle reminder that begging for a fix does not help making such fix become available faster. It gets out when it gets out.

i'm not a programer, i understand that it's might be difficult to fix the issue, but i just telling u what i have
+
i can't understand what this means ' While the issue can be replicated on my end with a v11.1 client (Insert key does not bring up skin changing menu), please supply the final state of the injector (showing whether injection was successful or not) instead of when the injector is waiting for the League client process. '
like if ' Insert ' doesn't bring up skin changing menu, then what brings it.

**Comment by 6oody** [comment]
and does B3akers can fix it or u guys r working togethier ?

**Comment by 6oody** [comment]
i tried it again and it's the same issuse, (Insert key does not bring up skin changing menu),
![image](https://user-images.githubusercontent.com/42409047/104058241-17553280-51fc-11eb-9b3d-c10f51ab5186.png)
